package com.linearframework.sql.query.retriever

import com.linearframework.sql.DatabaseException
import com.linearframework.sql.query.{Query, Row}

/**
  * Handles retrieval of a key generated by the database
  */
trait KeyRetriever[K] {

  /**
    * Executes the query, returning a generated key from the first row of the result set.
    */
  def execute(): K

}

private[sql] object KeyRetriever {

  def apply[K](query: Query, map: Row => K): KeyRetriever[K] = {
    new KeyRetrieverImpl(query, map)
  }

  private class KeyRetrieverImpl[K](private val query: Query, private val selectKey: Row => K) extends KeyRetriever[K] {
    override def execute(): K = {
      query.executeUpdate { rs =>
        if (rs.next()) {
          selectKey(new Row(rs))
        }
        else {
          throw new DatabaseException(s"Failed to retrieve generated key from query: ${query.sql}")
        }
      }
    }
  }

}