package com.linearframework.sql.query.retriever

import com.linearframework.sql.query.{Query, Row}
import scala.collection.mutable

/**
  * Handles retrieval of multiple keys generated by the database
  */
trait KeysRetriever[K] {

  /**
    * Executes the query, returning keys from each row of the result set.
    */
  def execute(): Seq[K]

}

private[sql] object KeysRetriever {

  def apply[K](query: Query, map: Row => K): KeysRetriever[K] = {
    new KeysRetrieverImpl(query, map)
  }

  private class KeysRetrieverImpl[K](private val query: Query, private val map: Row => K) extends KeysRetriever[K] {
    override def execute(): Seq[K] = {
      query.executeUpdate { rs =>
        val result = mutable.ListBuffer[K]()
        while (rs.next()) {
          result += map(new Row(rs))
        }
        result.toSeq
      }
    }
  }

}